---
title: "Lab#8"
author: "Mimosa Peeps"
date: "11/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
salmon<- read_csv("salmon.csv")
library(car)
library(plotly)
```

4. Exploratory Scatterplot

```{r}
scatter<- ggplot(salmon, aes(x =Year, y =Imports)) +
  geom_point()

scatter

# A linear regression makes sense for this data because imports v.s. year seems to be linearly related.
```

5. Linear Regression in R 

```{r}
#Linear regression for imports v.s year
salmon_model<- lm(Year~Imports, data = salmon)

salmon_model
```

imports(tons)= 0.000199 + 0.0000125(Year)
  - This means that every year 0.0000125 more tons of slamon are exported and that in year 0 0.000199 tons of salmon were exported.
  
6. Model Diagnostics

```{r}
plot(salmon_model)

#residuals appear normally distrubuted and there seems to be no concern over heteroscedacticity or outliers

par(mfrow = c(2,2))
plot(salmon_model)
```

7. Explore Model fit ans significance

```{r}
summary(salmon_model)

# The model signicicantly perdicts the salmon inports p-value = 0 (significantly =0)
# The R^2^ equal to 0.95 which indicates that 95% of salmon imports are determined by year
# 5% of salmon inports are not determined by year

```

8. Prepare a final graph

```{r}

salmon_graph<- ggplot(salmon, aes(x = Year, y = Imports))+
  geom_point()+
  geom_smooth(method = lm, se = TRUE, size = 0.5, color = "gray20")+
  theme_bw()+
  scale_x_continuous(expand = c(0,0), limits = c(1990,2017))+
 labs(x = "Year", y = "U.S. Annual Salmon Imports\n(1,000 pounds)")

salmon_graph
```

9. Making perdictions using the model

```{r}
future_years<- data.frame(year = c(2022, 2024, 2026, 2028))

perdictions<- predict(salmon_model, newdata = future_years, interval = "confidence")

perdictions


```




